trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# --- ÉTAPE 1: TÉLÉCHARGEMENT DE L'ARTEFACT ---
# Cette tâche doit s'exécuter en premier pour que le package soit disponible.
- task: DownloadBuildArtifacts@1
  displayName: 'Download Package from Previous Build'
  inputs:
    buildType: 'specific'
    project: 'f95c694d-f079-4e4b-bb88-89749cc5cffb'
    pipeline: '8'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'single'
    # IMPORTANT: Télécharge l'artefact dans le répertoire de l'agent.
    # L'emplacement par défaut est $(Pipeline.Workspace) ou $(System.ArtifactsDirectory)
    downloadPath: '$(System.ArtifactsDirectory)'

# --- ÉTAPE 2: DÉPLOIEMENT DE L'APPLICATION WEB ---
# Cette tâche s'exécute maintenant, après le téléchargement.
- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy Web App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Abonnement 2(a56f5503-7af4-45e6-8f96-dd6c75a8883d)'
    appType: 'webAppLinux'
    WebAppName: 'az-web-app6557669897'
    # IMPORTANT: Le chemin doit pointer vers l'endroit où l'artefact a été téléchargé.
    # Si le package a été téléchargé dans $(System.ArtifactsDirectory), 
    # vous devez ajuster le chemin pour le trouver.
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    RuntimeStack: 'PHP|8.3'
    DeploymentTypeLinux: 'oneDeploy'